orbs:
  webhook: eddiewebb/webhook@volatile
version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hi"
      - webhook/notify:
          endpoint: 'https://kmgcloud.ngrok.io/binge'
    working_directory: ~/repo
